on: [push]

jobs:
 
  install:
    runs-on: ubuntu-latest
    name: Install
    steps:
      # To use this repository's private action,
      # you must check out the repository
    - name: Checkout
      uses: actions/checkout@v2
    - run: |
        yarn install --frozen-lockfile

  build:
    runs-on: ubuntu-latest
    name: Build
    needs: install
    steps:
    # To use this repository's private action,
    # you must check out the repository
      # To use this repository's private action,
      # you must check out the repository
    - name: Checkout
      uses: actions/checkout@v2
    - run: |
        yarn install --frozen-lockfile;
        yarn run lint;
  # test:
  #   runs-on: ubuntu-latest
  #   name: Test
  #   needs: build
  #   steps:
  #   # To use this repository's private action,
  #   # you must check out the repository
  #   - name: Checkout
  #     uses: actions/checkout@v2
  #   - run: |
  #      yarn install;
  #      npm run test;
  # codecov:
  #   runs-on: ubuntu-latest
  #   name: Code Coverage
  #   needs: test
  #   steps:
  #   # To use this repository's private action,
  #   # you must check out the repository
  #   - name: Checkout
  #     uses: actions/checkout@v2
  #   - run: |
  #       npm install;
  #       npm run coverage;
  #       npm run codecov;
  #     env: # Or as an environment variable
  #       CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  publish:
    runs-on: ubuntu-latest
    name: Publish
    # needs: codecov
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: yarn install --frozen-lockfile
      - run: yarn run build
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

